# based on instructions from https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md
from python:3.11-alpine

# create service user for pyrod
RUN addgroup -S -g 111 pyrod
RUN adduser -S -D -H -u 111 -G pyrod pyrod

# copy built pyrod binary in
COPY target/x86_64-unknown-linux-musl/release/pyrod /bin

# copy this image's filesystem to the mounted filesystem
COPY scripts/copy-to-rootfs.sh .
RUN chmod +x copy-to-rootfs.sh
CMD ./copy-to-rootfs.sh